# For more information: https://laravel.com/docs/sail
version: '3'
services:
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    #     depends_on:
    #         - laravel.test
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3333:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '1234'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
